### ISSUE TITLE
Unable to run “npm start” shows error.

### ISSUE THREAD

**Issue by Orca-web** [kokororin/pixiv.moe#56]
![image](https://user-images.githubusercontent.com/59247295/104146130-8f8e4480-5404-11eb-8841-cbdb200a38d6.png)

**2021-01-11T03_58_16_379Z-debug.log**

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.13.4
3 info using node@v12.14.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pixiv.moe@1.6.1~prestart: pixiv.moe@1.6.1
6 info lifecycle pixiv.moe@1.6.1~start: pixiv.moe@1.6.1
7 verbose lifecycle pixiv.moe@1.6.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle pixiv.moe@1.6.1~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/pixiv.moe/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle pixiv.moe@1.6.1~start: CWD: /pixiv.moe
10 silly lifecycle pixiv.moe@1.6.1~start: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cross-env NODE_ENV=development TS_NODE_PROJECT="tsconfig-server.json" webpack-dev-server --config build/webpack.config.ts'
10 silly lifecycle ]
11 silly lifecycle pixiv.moe@1.6.1~start: Returned: code: 1  signal: null
12 info lifecycle pixiv.moe@1.6.1~start: Failed to exec start script
13 verbose stack Error: pixiv.moe@1.6.1 start: `cross-env NODE_ENV=development TS_NODE_PROJECT="tsconfig-server.json" webpack-dev-server --config build/webpack.config.ts`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:223:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:223:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid pixiv.moe@1.6.1
15 verbose cwd /pixiv.moe
16 verbose Linux 3.10.0-1127.19.1.el7.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v12.14.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error pixiv.moe@1.6.1 start: `cross-env NODE_ENV=development TS_NODE_PROJECT="tsconfig-server.json" webpack-dev-server --config build/webpack.config.ts`
22 error Exit status 1
23 error Failed at the pixiv.moe@1.6.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by kokororin** [comment]
Do not start dev server on Linux Server
